<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBlogPostTable extends Doctrine_Table
{
  public function retrieveLatestPosts($num)
  {
    $q = Doctrine::getTable('Content')
      ->getTypeQuery('BlogPost')
      ->orderBy('e.date_published DESC')
      ->limit($num);

    return $q->execute();
  }

  public function retrieveTopAuthors($num)
  {
    Doctrine::getTable('UserProfile');

    $q = Doctrine::getTable('Content')
      ->createQuery('e')
      ->select('*, count(ce.id) as num_posts')
      ->innerJoin('e.Type t2')
      ->innerJoin('e.UserProfile p')
      ->innerJoin('p.User u2')
      ->innerJoin('u2.CreatedContent ce')
      ->innerJoin('ce.Type t WITH t.name = ?', 'BlogPost')
      ->groupBy('e.id')
      ->limit($num);

    return $q->execute();
  }

  public function retrieveMonths()
  {
    return array(date('Y-m-d'));
  }

  public function retrieveBlogMonth($month, $year)
  {
    $start = date('Y-m-d', strtotime($month.'/01/'.$year));
    $end = date('Y-m-d', strtotime($start.' +1 month'));
    $end = date('Y-m-d', strtotime($end.' -1 day'));
    $dates = array($start, $end);

    Doctrine::getTable('BlogPost');

    $q = Doctrine::getTable('Content')
      ->createQuery('e')
      ->innerJoin('e.BlogPost p')
      ->innerJoin('e.Type t2')
      ->where('e.date_published > ? AND e.date_published < ?', $dates);
    
    $pager = new sfDoctrinePager('Content', sfSympalConfig::get('rows_per_page'));
    $pager->setQuery($q);
    $pager->init();

    return $pager;
  }
}